// <auto-generated />
using System;
using KLTN2025.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KLTN2025.Migrations
{
    [DbContext(typeof(KLTNContext))]
    [Migration("20251106184621_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KLTN2025.Models.GiaSu", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    b.Property<string>("AnhDaiDien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("AnhSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("BangCap")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BangTotNghiep")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("DaiHoc")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Chưa lên đại học");

                    b.Property<string>("KhuVucDay")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KinhNghiem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KyNang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LichRanh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NamBatDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("NamKetThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NganhHoc")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Chưa lên đại học");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<byte>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("TungHocTai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NguoiDungId");

                    b.ToTable("GiaSu", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.HoSoGiaSu", b =>
                {
                    b.Property<int>("HoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HoSoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoSoId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSDATETIME())");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int?>("NhanSuId")
                        .HasColumnType("int");

                    b.HasKey("HoSoId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("HoSoGiaSu", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.LopHoc", b =>
                {
                    b.Property<int>("LopHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LopHocID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopHocId"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GiaSuId")
                        .HasColumnType("int");

                    b.Property<decimal?>("HocPhi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte?>("KhoiLop")
                        .HasColumnType("tinyint");

                    b.Property<string>("LichHoc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MonHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSDATETIME())");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<int>("PhuHuynhId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Mới");

                    b.HasKey("LopHocId");

                    b.HasIndex("GiaSuId");

                    b.HasIndex("NhanSuId");

                    b.HasIndex("PhuHuynhId");

                    b.ToTable("LopHoc", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungId"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKhauHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("SDT");

                    b.Property<DateTime>("TaoVaoLuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSDATETIME())");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NguoiDungId");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.NhanSu", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NguoiDungId");

                    b.ToTable("NhanSu", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.PhanCong", b =>
                {
                    b.Property<int>("PhanCongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhanCongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanCongId"));

                    b.Property<int>("GiaSuId")
                        .HasColumnType("int");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSDATETIME())");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.HasKey("PhanCongId");

                    b.HasIndex("GiaSuId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("PhanCong", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.PhanHoi", b =>
                {
                    b.Property<int>("PhanHoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhanHoiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanHoiId"));

                    b.Property<byte>("DiemDanhGia")
                        .HasColumnType("tinyint");

                    b.Property<string>("LoaiPhanHoi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSDATETIME())");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhanHoiId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("PhanHoi", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.PhieuHoTro", b =>
                {
                    b.Property<int>("PhieuHoTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhieuHoTroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuHoTroId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayGiaiQuyet")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<int>("PhanHoiId")
                        .HasColumnType("int");

                    b.HasKey("PhieuHoTroId");

                    b.HasIndex("NhanSuId");

                    b.HasIndex("PhanHoiId");

                    b.ToTable("PhieuHoTro", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThanhToanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanId"));

                    b.Property<int>("GiaSuId")
                        .HasColumnType("int");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSDATETIME())");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang chờ");

                    b.HasKey("ThanhToanId");

                    b.HasIndex("GiaSuId");

                    b.HasIndex("LopHocId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.ThongBao", b =>
                {
                    b.Property<int>("ThongBaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThongBaoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThongBaoId"));

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSDATETIME())");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ThongBaoId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.UngTuyen", b =>
                {
                    b.Property<int>("UngTuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UngTuyenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UngTuyenId"));

                    b.Property<int>("GiaSuId")
                        .HasColumnType("int");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayUngTuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSDATETIME())");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang chờ");

                    b.HasKey("UngTuyenId");

                    b.HasIndex("GiaSuId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("UngTuyen", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.GiaSu", b =>
                {
                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("GiaSus")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_GiaSu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KLTN2025.Models.HoSoGiaSu", b =>
                {
                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("HoSoGiaSus")
                        .HasForeignKey("NguoiDungId")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_HoSoGiaSu");

                    b.HasOne("KLTN2025.Models.NhanSu", "NhanSu")
                        .WithMany("HoSoGiaSus")
                        .HasForeignKey("NhanSuId")
                        .HasConstraintName("FK_NhanSuID_HoSoGiaSu");

                    b.Navigation("NguoiDung");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("KLTN2025.Models.LopHoc", b =>
                {
                    b.HasOne("KLTN2025.Models.GiaSu", "GiaSu")
                        .WithMany("LopHocsGiaSu")
                        .HasForeignKey("GiaSuId")
                        .IsRequired()
                        .HasConstraintName("FK_GiaSuID_LopHoc");

                    b.HasOne("KLTN2025.Models.NhanSu", "NhanSu")
                        .WithMany("LopHocsNhanSu")
                        .HasForeignKey("NhanSuId")
                        .IsRequired()
                        .HasConstraintName("FK_NhanSuID_LopHoc");

                    b.HasOne("KLTN2025.Models.NguoiDung", "PhuHuynh")
                        .WithMany("LopHocsPhuHuynh")
                        .HasForeignKey("PhuHuynhId")
                        .IsRequired()
                        .HasConstraintName("FK_PhuHuynhID_LopHoc");

                    b.Navigation("GiaSu");

                    b.Navigation("NhanSu");

                    b.Navigation("PhuHuynh");
                });

            modelBuilder.Entity("KLTN2025.Models.NhanSu", b =>
                {
                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhanSus")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_NhanSu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KLTN2025.Models.PhanCong", b =>
                {
                    b.HasOne("KLTN2025.Models.GiaSu", "GiaSu")
                        .WithMany("PhanCongs")
                        .HasForeignKey("GiaSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GiaSuID_PhanCong");

                    b.HasOne("KLTN2025.Models.LopHoc", "LopHoc")
                        .WithMany("PhanCongs")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LopHocID_PhanCong");

                    b.HasOne("KLTN2025.Models.NhanSu", "NhanSu")
                        .WithMany("PhanCongs")
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NhanSuID_PhanCong");

                    b.Navigation("GiaSu");

                    b.Navigation("LopHoc");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("KLTN2025.Models.PhanHoi", b =>
                {
                    b.HasOne("KLTN2025.Models.LopHoc", "LopHoc")
                        .WithMany("PhanHois")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LopHocID_PhanHoi");

                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhanHois")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_PhanHoi");

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KLTN2025.Models.PhieuHoTro", b =>
                {
                    b.HasOne("KLTN2025.Models.NhanSu", "NhanSu")
                        .WithMany("PhieuHoTros")
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NhanSuIID_PhieuHoTro");

                    b.HasOne("KLTN2025.Models.PhanHoi", "PhanHoi")
                        .WithMany("PhieuHoTros")
                        .HasForeignKey("PhanHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PhanHoiID_PhieuHoTro");

                    b.Navigation("NhanSu");

                    b.Navigation("PhanHoi");
                });

            modelBuilder.Entity("KLTN2025.Models.ThanhToan", b =>
                {
                    b.HasOne("KLTN2025.Models.GiaSu", "GiaSu")
                        .WithMany("ThanhToans")
                        .HasForeignKey("GiaSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GiaSuID_ThanhToan");

                    b.HasOne("KLTN2025.Models.LopHoc", "LopHoc")
                        .WithMany("ThanhToans")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LopHocID_ThanhToan");

                    b.Navigation("GiaSu");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("KLTN2025.Models.ThongBao", b =>
                {
                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_ThongBao");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KLTN2025.Models.UngTuyen", b =>
                {
                    b.HasOne("KLTN2025.Models.GiaSu", "GiaSu")
                        .WithMany("UngTuyens")
                        .HasForeignKey("GiaSuId")
                        .IsRequired()
                        .HasConstraintName("FK_GiaSuID_UngTuyen");

                    b.HasOne("KLTN2025.Models.LopHoc", "LopHoc")
                        .WithMany("UngTuyens")
                        .HasForeignKey("LopHocId")
                        .IsRequired()
                        .HasConstraintName("FK_LopHocID_UngTuyen");

                    b.HasOne("KLTN2025.Models.NhanSu", "NhanSu")
                        .WithMany("UngTuyens")
                        .HasForeignKey("NhanSuId")
                        .IsRequired()
                        .HasConstraintName("FK_NhanSuID_UngTuyen");

                    b.Navigation("GiaSu");

                    b.Navigation("LopHoc");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("KLTN2025.Models.GiaSu", b =>
                {
                    b.Navigation("LopHocsGiaSu");

                    b.Navigation("PhanCongs");

                    b.Navigation("ThanhToans");

                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("KLTN2025.Models.LopHoc", b =>
                {
                    b.Navigation("PhanCongs");

                    b.Navigation("PhanHois");

                    b.Navigation("ThanhToans");

                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("KLTN2025.Models.NguoiDung", b =>
                {
                    b.Navigation("GiaSus");

                    b.Navigation("HoSoGiaSus");

                    b.Navigation("LopHocsPhuHuynh");

                    b.Navigation("NhanSus");

                    b.Navigation("PhanHois");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("KLTN2025.Models.NhanSu", b =>
                {
                    b.Navigation("HoSoGiaSus");

                    b.Navigation("LopHocsNhanSu");

                    b.Navigation("PhanCongs");

                    b.Navigation("PhieuHoTros");

                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("KLTN2025.Models.PhanHoi", b =>
                {
                    b.Navigation("PhieuHoTros");
                });
#pragma warning restore 612, 618
        }
    }
}
