// <auto-generated />
using System;
using KLTN2025.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KLTN2025.Migrations
{
    [DbContext(typeof(KLTNContext))]
    partial class KLTNContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KLTN2025.Models.GiaSu", b =>
                {
                    b.Property<int>("GiaSuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GiaSuID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiaSuId"));

                    b.Property<string>("AnhDaiDien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("AnhSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("BangCap")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BangTotNghiep")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("DaiHoc")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Chua lên d?i h?c");

                    b.Property<string>("KhuVucDay")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KinhNghiem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KyNang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LichRanh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NamBatDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("NamKetThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NganhHoc")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Chua lên d?i h?c");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TungHocTai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GiaSuId")
                        .HasName("PK__GiaSu__BE5E202748DD713A");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("GiaSu", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.HoSoGiaSu", b =>
                {
                    b.Property<int>("HoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HoSoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoSoId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GiaSuId")
                        .HasColumnType("int")
                        .HasColumnName("GiaSuID");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("NhanSuId")
                        .HasColumnType("int")
                        .HasColumnName("NhanSuID");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("Đang chờ");

                    b.Property<string>("TuChoiVi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("HoSoId")
                        .HasName("PK__HoSoGiaS__A9F1AA18CB5B53F2");

                    b.HasIndex("GiaSuId");

                    b.ToTable("HoSoGiaSu", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.LopHoc", b =>
                {
                    b.Property<int>("LopHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LopHocID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopHocId"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GiaSuId")
                        .HasColumnType("int")
                        .HasColumnName("GiaSuID");

                    b.Property<decimal?>("HocPhi")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<byte?>("KhoiLop")
                        .HasColumnType("tinyint");

                    b.Property<string>("LichHoc")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MonHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int")
                        .HasColumnName("NhanSuID");

                    b.Property<int>("PhuHuynhId")
                        .HasColumnType("int")
                        .HasColumnName("PhuHuynhID");

                    b.Property<byte?>("SoBuoiHoc")
                        .HasColumnType("tinyint");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Mới");

                    b.HasKey("LopHocId")
                        .HasName("PK__LopHoc__DBC489C09B45C547");

                    b.HasIndex("PhuHuynhId");

                    b.ToTable("LopHoc", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKhauHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("SDT");

                    b.Property<DateTime>("TaoVaoLuc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NguoiDungId")
                        .HasName("PK__NguoiDun__C4BBA4DDE679DE91");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NguoiDun__55F68FC067D430D1")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D105346EFE860E")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.NhanSu", b =>
                {
                    b.Property<int>("NhanSuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NhanSuID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanSuId"));

                    b.Property<string>("BoPhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    b.HasKey("NhanSuId")
                        .HasName("PK__NhanSu__F2329F1BB51D7490");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhanSu", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.PhanCong", b =>
                {
                    b.Property<int>("PhanCongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhanCongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanCongId"));

                    b.Property<int>("GiaSuId")
                        .HasColumnType("int")
                        .HasColumnName("GiaSuID");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocID");

                    b.Property<DateTime>("NgayPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int")
                        .HasColumnName("NhanSuID");

                    b.HasKey("PhanCongId")
                        .HasName("PK__PhanCong__7EF840DDA0E8DEE5");

                    b.HasIndex("GiaSuId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("PhanCong", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.PhanHoi", b =>
                {
                    b.Property<int>("PhanHoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhanHoiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanHoiId"));

                    b.Property<byte>("DiemDanhGia")
                        .HasColumnType("tinyint");

                    b.Property<string>("LoaiPhanHoi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocID");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang chờ");

                    b.HasKey("PhanHoiId")
                        .HasName("PK__PhanHoi__7480288BB26D542F");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("PhanHoi", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.PhieuHoTro", b =>
                {
                    b.Property<int>("PhieuHoTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhieuHoTroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuHoTroId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int")
                        .HasColumnName("NhanSuID");

                    b.Property<int>("PhanHoiId")
                        .HasColumnType("int")
                        .HasColumnName("PhanHoiID");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang chờ");

                    b.HasKey("PhieuHoTroId")
                        .HasName("PK__PhieuHoT__6A7F0FDCD2C2ECC5");

                    b.HasIndex("NhanSuId");

                    b.HasIndex("PhanHoiId");

                    b.ToTable("PhieuHoTro", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.PhuHuynh", b =>
                {
                    b.Property<int>("PhuHuynhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhuHuynhID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhuHuynhId"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    b.HasKey("PhuHuynhId")
                        .HasName("PK__PhuHuynh__D0ADD09079B8831A");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("PhuHuynh", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThanhToanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanId"));

                    b.Property<int>("GiaSuId")
                        .HasColumnType("int")
                        .HasColumnName("GiaSuID");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocID");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang chờ");

                    b.HasKey("ThanhToanId")
                        .HasName("PK__ThanhToa__24A8D684973C0587");

                    b.HasIndex("GiaSuId");

                    b.HasIndex("LopHocId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.ThongBao", b =>
                {
                    b.Property<int>("ThongBaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThongBaoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThongBaoId"));

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThongBaoId")
                        .HasName("PK__ThongBao__6E51A53B0FEA1A6B");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.UngTuyen", b =>
                {
                    b.Property<int>("UngTuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UngTuyenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UngTuyenId"));

                    b.Property<int>("GiaSuId")
                        .HasColumnType("int")
                        .HasColumnName("GiaSuID");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocID");

                    b.Property<DateTime>("NgayUngTuyen")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang chờ");

                    b.HasKey("UngTuyenId")
                        .HasName("PK__UngTuyen__4E510296DAF8E723");

                    b.HasIndex("GiaSuId");

                    b.HasIndex("LopHocId");

                    b.ToTable("UngTuyen", (string)null);
                });

            modelBuilder.Entity("KLTN2025.Models.GiaSu", b =>
                {
                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("GiaSus")
                        .HasForeignKey("NguoiDungId")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_GiaSu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KLTN2025.Models.HoSoGiaSu", b =>
                {
                    b.HasOne("KLTN2025.Models.GiaSu", "GiaSu")
                        .WithMany("HoSoGiaSus")
                        .HasForeignKey("GiaSuId")
                        .IsRequired()
                        .HasConstraintName("FK_GiaSuID_HoSoGiaSu");

                    b.Navigation("GiaSu");
                });

            modelBuilder.Entity("KLTN2025.Models.LopHoc", b =>
                {
                    b.HasOne("KLTN2025.Models.PhuHuynh", "PhuHuynh")
                        .WithMany("LopHocs")
                        .HasForeignKey("PhuHuynhId")
                        .IsRequired()
                        .HasConstraintName("FK_PhuHuynhID_LopHoc");

                    b.Navigation("PhuHuynh");
                });

            modelBuilder.Entity("KLTN2025.Models.NhanSu", b =>
                {
                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhanSus")
                        .HasForeignKey("NguoiDungId")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_NhanSu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KLTN2025.Models.PhanCong", b =>
                {
                    b.HasOne("KLTN2025.Models.GiaSu", "GiaSu")
                        .WithMany("PhanCongs")
                        .HasForeignKey("GiaSuId")
                        .IsRequired()
                        .HasConstraintName("FK_GiaSuID_PhanCong");

                    b.HasOne("KLTN2025.Models.LopHoc", "LopHoc")
                        .WithMany("PhanCongs")
                        .HasForeignKey("LopHocId")
                        .IsRequired()
                        .HasConstraintName("FK_LopHocID_PhanCong");

                    b.HasOne("KLTN2025.Models.NhanSu", "NhanSu")
                        .WithMany("PhanCongs")
                        .HasForeignKey("NhanSuId")
                        .IsRequired()
                        .HasConstraintName("FK_NhanSuID_PhanCong");

                    b.Navigation("GiaSu");

                    b.Navigation("LopHoc");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("KLTN2025.Models.PhanHoi", b =>
                {
                    b.HasOne("KLTN2025.Models.LopHoc", "LopHoc")
                        .WithMany("PhanHois")
                        .HasForeignKey("LopHocId")
                        .IsRequired()
                        .HasConstraintName("FK_LopHocID_PhanHoi");

                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhanHois")
                        .HasForeignKey("NguoiDungId")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_PhanHoi");

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KLTN2025.Models.PhieuHoTro", b =>
                {
                    b.HasOne("KLTN2025.Models.NhanSu", "NhanSu")
                        .WithMany("PhieuHoTros")
                        .HasForeignKey("NhanSuId")
                        .IsRequired()
                        .HasConstraintName("FK_NhanSuIID_PhieuHoTro");

                    b.HasOne("KLTN2025.Models.PhanHoi", "PhanHoi")
                        .WithMany("PhieuHoTros")
                        .HasForeignKey("PhanHoiId")
                        .IsRequired()
                        .HasConstraintName("FK_PhanHoiID_PhieuHoTro");

                    b.Navigation("NhanSu");

                    b.Navigation("PhanHoi");
                });

            modelBuilder.Entity("KLTN2025.Models.PhuHuynh", b =>
                {
                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhuHuynhs")
                        .HasForeignKey("NguoiDungId")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_PhuHuynh");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KLTN2025.Models.ThanhToan", b =>
                {
                    b.HasOne("KLTN2025.Models.GiaSu", "GiaSu")
                        .WithMany("ThanhToans")
                        .HasForeignKey("GiaSuId")
                        .IsRequired()
                        .HasConstraintName("FK_GiaSuID_ThanhToan");

                    b.HasOne("KLTN2025.Models.LopHoc", "LopHoc")
                        .WithMany("ThanhToans")
                        .HasForeignKey("LopHocId")
                        .IsRequired()
                        .HasConstraintName("FK_LopHocID_ThanhToan");

                    b.Navigation("GiaSu");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("KLTN2025.Models.ThongBao", b =>
                {
                    b.HasOne("KLTN2025.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiDungId")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDungID_ThongBao");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KLTN2025.Models.UngTuyen", b =>
                {
                    b.HasOne("KLTN2025.Models.GiaSu", "GiaSu")
                        .WithMany("UngTuyens")
                        .HasForeignKey("GiaSuId")
                        .IsRequired()
                        .HasConstraintName("FK_GiaSuID_UngTuyen");

                    b.HasOne("KLTN2025.Models.LopHoc", "LopHoc")
                        .WithMany("UngTuyens")
                        .HasForeignKey("LopHocId")
                        .IsRequired()
                        .HasConstraintName("FK_LopHocID_UngTuyen");

                    b.Navigation("GiaSu");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("KLTN2025.Models.GiaSu", b =>
                {
                    b.Navigation("HoSoGiaSus");

                    b.Navigation("PhanCongs");

                    b.Navigation("ThanhToans");

                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("KLTN2025.Models.LopHoc", b =>
                {
                    b.Navigation("PhanCongs");

                    b.Navigation("PhanHois");

                    b.Navigation("ThanhToans");

                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("KLTN2025.Models.NguoiDung", b =>
                {
                    b.Navigation("GiaSus");

                    b.Navigation("NhanSus");

                    b.Navigation("PhanHois");

                    b.Navigation("PhuHuynhs");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("KLTN2025.Models.NhanSu", b =>
                {
                    b.Navigation("PhanCongs");

                    b.Navigation("PhieuHoTros");
                });

            modelBuilder.Entity("KLTN2025.Models.PhanHoi", b =>
                {
                    b.Navigation("PhieuHoTros");
                });

            modelBuilder.Entity("KLTN2025.Models.PhuHuynh", b =>
                {
                    b.Navigation("LopHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
